### ISSUE TITLE
TeXLive fonts are not configured via fontconfig

### ISSUE THREAD

**Issue by maciej-lech** [xu-cheng/latex-docker#10]
Hi!

Fonts can not be found when using `XeLaTeX`+`fontspec` because they are not visible in the system via `fontconfig`.
```
Package fontspec Error: The font "Latin Modern Roman" cannot be found.

For immediate help type H <return>.
 ...                                              
                                                  
l.87 \setromanfont
                  {Latin Modern Roman}
No pages of output.
```

The possible solution is to link the `fonconfig` configuration file from the `TeXLive` installation path to the `/etc/fonts/conf.d/` and reload the cache.
```
$ ln -s $(kpsewhich -var-value TEXMFSYSVAR)/fonts/conf/texlive-fontconfig.conf /etc/fonts/conf.d/65-texlive-fontconfig.conf
$ fc-cache
```

You may want to add it to the `setup.sh`. I can bake a PR if this solution is ok.

Best regards

**Comment by xu-cheng** [comment]
A PR is welcomed.
