### ISSUE TITLE
Could you trigger a manual build?

### ISSUE THREAD

**Issue by paddyroddy** [xu-cheng/latex-docker#14]
My CI recently started failing - I think since the last scheduled build on 1st August. I then updated my local `texlive` and found I encountered the same build problems. I've just updated my `texlive` and whatever the problem has since been fixed.

Not entirely sure what the problem was, but it was to do with using commands such as `\RomanNumeralCaps`. Cheers!

**Comment by xu-cheng** [comment]
Done. https://github.com/xu-cheng/latex-docker/actions/runs/2816643577

**Comment by paddyroddy** [comment]
Thank you! Worked a treat
