### ISSUE TITLE
Inkscape dependency

### ISSUE THREAD

**Issue by drupol** [xu-cheng/latex-docker#3]
Hello,

I'd like to include SVG files in my LaTeX documents.

I'm currently using:

`\includesvg[width=0.5\columnwidth, svgpath=style/logo/]{logo.svg}`

But it requires `inkscape`.

What's the best option I have in this case? Should I install [inkscape](https://pkgs.alpinelinux.org/package/edge/community/x86/inkscape) in the Docker container?

What do you advise?

**Comment by xu-cheng** [comment]
You should be able to install it by just running  `apk add inkscape` in the container.

**Comment by xu-cheng** [comment]
Also, personally, I would avoid using svg figures. It is recommended to use pdf or eps format instead.

**Comment by drupol** [comment]
Fair enough, I will use .pdf or .eps.

Thanks for your feedback!
