### ISSUE TITLE
Consider adding make(1) to the image

### ISSUE THREAD

**Issue by jmarshall** [xu-cheng/latex-docker#9]
We have CI scripts using a no-longer-updated LaTeX image that I'd like to move to using this nicely built image instead. Our scripts (see [samtools/hts-specs](https://github.com/samtools/hts-specs/blob/master/Makefile) and that repo's _.circleci/config.yml_) are set up to use `make` to determine which LaTeX documents to rebuild, prepare various things, and run `latexmk` (actually currently our own script, but we'll soon switch to `latexmk`).

Would you consider adding [make](https://pkgs.alpinelinux.org/package/v3.13/main/x86_64/make) to your image? Fortunately it's quite small — ~250K.

(We also use `git`, which is rather larger. But I plan to work around not having that in a different way.)

**Comment by xu-cheng** [comment]
Can you just simply run `apk add make` in the beginning of your workflow?

**Comment by jmarshall** [comment]
I'm aiming to switch these scripts to GitHub Actions and would use this image only for the job step that needs LaTeX. So I wouldn't be able to have this in an initialisation step at the top of the workflow, rather it would have to be mixed into the image-using step's scripts.

For example, if I ended up using your latex-action, it might be something like

```yaml
uses: xu-cheng/latex-action@v2
with:
  pre_compile: "apk add make; make …etc…"
  root_file: ${{ env.filelist_from_previous_step }}
```

So that would indeed be a somewhat viable workaround.

But to be honest, if I was going to start installing stuff, I'd probably just use GH's ubuntu-latest image and `apt-get install texlive` and call it a feature that CI had a somewhat conservative older set of LaTeX packages…

**Comment by xu-cheng** [comment]
I suggest you to use https://github.com/xu-cheng/texlive-action to compile your latex document. Please see the example in its README file.

**Comment by jmarshall** [comment]
Thank you, I had looked at that one briefly but clearly not carefully enough.

Clearly you have considered `make` and think its use is common enough to have as an example, but have rejected pre-installing it. This seems surprising when the image contains a Perl installation and two Python installations, which rather outweigh the make package's size, but fair enough.

**Comment by xu-cheng** [comment]
> This seems surprising when the image contains a Perl installation and two Python installations

FYI, Perl and Python are needed by a various of tools shipped by TeXLive. TeXLive only ships these tools in source scripts without interpreters. As such, we are requested to preinstalled them in the docker image.
